#gemini_symbols.py

#All possible crypto currencies available in gemini and the minimum decimal spaces for a purchase
def gemini_symbols():
    gravit = {
    "BTCUSD" : 5,
    "ETHUSD" : 3,
    "LTCUSD" : 2,
    "BCHUSD" : 3,
    "ZECUSD" : 3,
    "LINKUSD" : 1,
    "OXTUSD" : 0,
    "DAIUSD" : 1,
    "BATUSD" : 0,
    "AMPUSD" : -1,
    "COMPUSD" : 3,
    "CTXUSD" : 3,
    "PAXGUSD" : 4,
    "ZRXUSD" : 1,
    "BALUSD" : 2,
    "CRVUSD" : 1,
    "MANAUSD" : 0,
    "KNCUSD" : 1,
    "MKRUSD" : 3,
    "RENUSD" : 2,
    "STORJUSD" : 1,
    "SNXUSD" : 2,
    "UMAUSD" : 2,
    "UNIUSD" : 2,
    "YFIUSD" : 5,
    "AAVEUSD" : 3,
    "FILUSD" : 1,
    "SKLUSD" : 1,
    "GRTUSD" : 1,
    "BNTUSD" : 2,
    "1INCHUSD" : 2,
    "ENJUSD" : 1,
    "LRCUSD" : 1,
    "SANDUSD" : 1,
    "CUBEUSD" : 2,
    "BONDUSD" : 3,
    "INJUSD" : 2,
    "LPTUSD" : 3,
    "MATICUSD" : 1,
    "SUSHIUSD" : 2,
    "DOGEUSD" : 1,
    "ANKRUSD" : 1,
    "MIRUSD" : 3,
    "FTMUSD" : 2,
    "ALCXUSD" : 5,
    "XTZUSD" : 2
    }
    return gravit
